# det_train.yaml
path: /content/datasets
train: manifests/train.txt
val: manifests/val.txt
label_dir: labels/detection
cache: /content/datasets/cache

nc: 8
names:
  0: crack_paint
  1: paint_peel_paint
  2: paint_separation_paint
  3: paint_flow_paint
  4: insulation_damage_insulation
  5: scratch_paint
  6: scratch_base
  7: scratch_insulation
