name: siren
description: LNG Tank Inspection System — Field Tablet App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Network
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # Image
  cached_network_image: ^3.3.1

  # Camera / Gallery
  image_picker: ^1.1.1

  # Date formatting
  intl: ^0.19.0

  # Fonts
  google_fonts: ^6.2.1

  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
